//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login field is required.
        /// </summary>
        internal static string Credentials_LoginFieldIsRequired {
            get {
                return ResourceManager.GetString("Credentials_LoginFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password field is required.
        /// </summary>
        internal static string Credentials_PasswordFieldIsRequired {
            get {
                return ResourceManager.GetString("Credentials_PasswordFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Index_ButtonSubmit {
            get {
                return ResourceManager.GetString("Index_ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are here.
        /// </summary>
        internal static string Index_Header {
            get {
                return ResourceManager.GetString("Index_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Index_Login {
            get {
                return ResourceManager.GetString("Index_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Index_Password {
            get {
                return ResourceManager.GetString("Index_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate user fail.
        /// </summary>
        internal static string Index_ValidateUserFail {
            get {
                return ResourceManager.GetString("Index_ValidateUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string MainLayout_LogOut {
            get {
                return ResourceManager.GetString("MainLayout_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string ProductCatalog_ButtonAddToOrder {
            get {
                return ResourceManager.GetString("ProductCatalog_ButtonAddToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string ProductCatalog_ButtonRemoveFromOrder {
            get {
                return ResourceManager.GetString("ProductCatalog_ButtonRemoveFromOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ProductCatalog_ButtonSearch {
            get {
                return ResourceManager.GetString("ProductCatalog_ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose products for youself!.
        /// </summary>
        internal static string ProductCatalog_Header {
            get {
                return ResourceManager.GetString("ProductCatalog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string ProductCatalog_HeaderCategory {
            get {
                return ResourceManager.GetString("ProductCatalog_HeaderCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string ProductCatalog_HeaderCount {
            get {
                return ResourceManager.GetString("ProductCatalog_HeaderCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ProductCatalog_HeaderName {
            get {
                return ResourceManager.GetString("ProductCatalog_HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string ProductCatalog_HeaderPrice {
            get {
                return ResourceManager.GetString("ProductCatalog_HeaderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string ProductCatalog_PagerFirstLink {
            get {
                return ResourceManager.GetString("ProductCatalog_PagerFirstLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string ProductCatalog_PagerLastLink {
            get {
                return ResourceManager.GetString("ProductCatalog_PagerLastLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string ProductCatalog_PagerNextLink {
            get {
                return ResourceManager.GetString("ProductCatalog_PagerNextLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        internal static string ProductCatalog_PagerPrevLink {
            get {
                return ResourceManager.GetString("ProductCatalog_PagerPrevLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        internal static string ProductCatalog_SearchCategory {
            get {
                return ResourceManager.GetString("ProductCatalog_SearchCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string ProductCatalog_SearchName {
            get {
                return ResourceManager.GetString("ProductCatalog_SearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in catalog.
        /// </summary>
        internal static string ProductCatalog_SearchText {
            get {
                return ResourceManager.GetString("ProductCatalog_SearchText", resourceCulture);
            }
        }
    }
}
