//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.19050
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Login field is required.
        /// </summary>
        internal static string Credentials_LoginFieldIsRequired {
            get {
                return ResourceManager.GetString("Credentials_LoginFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Password field is required.
        /// </summary>
        internal static string Credentials_PasswordFieldIsRequired {
            get {
                return ResourceManager.GetString("Credentials_PasswordFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Submit.
        /// </summary>
        internal static string Index_ButtonSubmit {
            get {
                return ResourceManager.GetString("Index_ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как You are here.
        /// </summary>
        internal static string Index_Header {
            get {
                return ResourceManager.GetString("Index_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Login.
        /// </summary>
        internal static string Index_Login {
            get {
                return ResourceManager.GetString("Index_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Password.
        /// </summary>
        internal static string Index_Password {
            get {
                return ResourceManager.GetString("Index_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Validate user fail.
        /// </summary>
        internal static string Index_ValidateUserFail {
            get {
                return ResourceManager.GetString("Index_ValidateUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Log Out.
        /// </summary>
        internal static string MainLayout_LogOut {
            get {
                return ResourceManager.GetString("MainLayout_LogOut", resourceCulture);
            }
        }
    }
}
