//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.MvcWebProject.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineStore.MvcWebProject.App_GlobalResources.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/jpg;base64,.
        /// </summary>
        internal static string Base64StringBegin {
            get {
                return ResourceManager.GetString("Base64StringBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentPageIndexBasket.
        /// </summary>
        internal static string Basket_OldPageIndexName {
            get {
                return ResourceManager.GetString("Basket_OldPageIndexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to system.net/mailSettings/smtp.
        /// </summary>
        internal static string Basket_SmtpSectionPath {
            get {
                return ResourceManager.GetString("Basket_SmtpSectionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoughtInStorage.
        /// </summary>
        internal static string BoughtInStorage {
            get {
                return ResourceManager.GetString("BoughtInStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentPageIndexCatalog.
        /// </summary>
        internal static string Catalog_OldPageIndexName {
            get {
                return ResourceManager.GetString("Catalog_OldPageIndexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchCategoryCatalog.
        /// </summary>
        internal static string Catalog_SearchCategoryInStorage {
            get {
                return ResourceManager.GetString("Catalog_SearchCategoryInStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchNameCatalog.
        /// </summary>
        internal static string Catalog_SearchNameInStorage {
            get {
                return ResourceManager.GetString("Catalog_SearchNameInStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencyInStorage.
        /// </summary>
        internal static string CurrencyInStorage {
            get {
                return ResourceManager.GetString("CurrencyInStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentPageIndexManagement.
        /// </summary>
        internal static string Management_OldPageIndexName {
            get {
                return ResourceManager.GetString("Management_OldPageIndexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewUser.
        /// </summary>
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentOrder.
        /// </summary>
        internal static string OrderInStorage {
            get {
                return ResourceManager.GetString("OrderInStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentPageIndexProfile.
        /// </summary>
        internal static string Profile_OldPageIndexName {
            get {
                return ResourceManager.GetString("Profile_OldPageIndexName", resourceCulture);
            }
        }
    }
}
